# Generated by Django 2.2 on 2020-02-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_auto_20200208_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='label',
            new_name='label_note',
        ),
    ]
