# Generated by Django 2.2 on 2020-02-15 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_auto_20200214_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='user_id',
        ),
    ]
