# Generated by Django 2.2 on 2020-02-15 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0011_remove_label_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Label_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
