# Generated by Django 2.2 on 2020-02-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0013_auto_20200215_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='label_note',
            new_name='label',
        ),
    ]
