# Generated by Django 2.2 on 2020-02-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0017_auto_20200217_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
    ]
