# Generated by Django 2.2 on 2020-01-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='pasword1',
            new_name='password2',
        ),
    ]
