# Generated by Django 2.2 on 2020-01-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20200122_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password1',
            new_name='password',
        ),
    ]
