# Generated by Django 2.2 on 2020-02-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20200220_0419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
