# Generated by Django 2.2 on 2020-02-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_profile'),
    ]

    operations = [
    ]
